shell="nu"

[window]
opacity = 0.9

[font]
size = $alacritty_font_size

[keyboard]
bindings=[
	{ key ="F", mods="Control", action="SearchForward" },
	{ key ="B",	mods="Control", action="SearchBackward"},
]
