# MAIN COLORS
#f72585
#7209b7
#3a0ca3
#4361ee
#4cc9f0

format = """
$shell\
[ ](bg:#f72585)\
$sudo$username$hostname\
[ ](bg:#f72585)\
[ ](fg:#f72585 bg:#7209b7)\
$directory\
[ ](bg:#7209b7)\
[ ](fg:#7209b7 bg:#3a0ca3)\
$git_branch$git_metrics\
[ ](bg:#3a0ca3)\
[ ](fg:#3a0ca3 bg:#4361ee)\
$c\
$dotnet\
$golang\
$java\
$nodejs\
$python\
$rust\
$docker_context\
[ ](bg:#4361ee)\
[](fg:#4361ee bg:black)
$cmd_duration$status$character\
"""

### SHELL ###
[shell]
disabled = false
nu_indicator = '' # hide it as it's the default
style = "fg:white bg:#f72585"
format = "[$indicator]($style)"

[sudo]
disabled = false
style = "fg:white bg:#f72585"
symbol = " "
format = "[$symbol]($style)"

[username]
show_always = true
style_user = "fg:white bg:#f72585"
style_root = "fg:white bg:#f72585"
format = '[$user]($style)'

[hostname]
ssh_only = false
style = "bg:#f72585"
format = "[@$hostname$ssh_symbol]($style)"

### DIRECTORY ###
[directory]
style = "bg:#7209b7"
format = "[$read_only$path]($style)"
truncation_length = 3

#[directory.substitutions]
#"Documents" = " "
#"Downloads" = " "
#"Music" = " "
#"Pictures" = " "
#"games" = " "
#"code" = " "
#"rust" = ""
#"dotnet" = " "
#"java" = ""
#"cpp" = " "

### GIT ###
[git_branch]
symbol = ""
style = "bg:#3a0ca3"
format = '[$symbol$branch]($style)'
ignore_branches = ["main","master"]

[git_metrics]
disabled = false
added_style = "fg:#06d6a0 bg:#3a0ca3"
deleted_style = "fg:#f72585 bg:#3a0ca3"
format = "([+$added]($added_style))([-$deleted]($deleted_style))"

# TODO: what about git commit, state and status?

# langs
[c]
symbol = " "
style = "bg:#4361ee"
format = '[$symbol($version)]($style)'

[docker_context]
symbol = " "
style = "bg:#4361ee"
format = '[$symbol$context]($style) $path'

[dotnet]
symbol = ""
style = "bg:#4361ee"
format = '[$symbol ($version)]($style)'

[golang]
symbol = ""
style = "bg:#4361ee"
format = '[$symbol ($version)]($style)'

[java]
symbol = ""
style = "bg:#4361ee"
format = '[$symbol ($version)]($style)'

[nodejs]
symbol = ""
style = "bg:#4361ee"
format = '[$symbol ($version)]($style)'

[python]
symbol = ""
style = "bg:#4361ee"
format = '[$symbol ($version)]($style)'

[rust]
symbol = ""
style = "bg:#4361ee"
format = '[$symbol ($version)]($style)'

### END ###
[cmd_duration]
format = "[$duration]($style)"
style = "#4cc9f0"
min_time = 2_000

[status]
disabled = false
format = "[$symbol$status]($style)"
style = "#f72585"
map_symbol = true

[character]
success_symbol = "[❯](#4cc9f0)"
error_symbol = "[❯](#f72585)"
# vimcmd_symbol = "[❮](green)"
