[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "--cfg", "tokio_unstable"]

#[unstable]
#codegen-backend = true

#profile.dev]
#codegen-backend = "cranelift"
